# Generated by Django 3.1.5 on 2021-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_giver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Fundation'), (2, 'Non-governmental organization'), (3, 'Local collection')], default=1)),
                ('categories', models.ManyToManyField(to='clothes_giver.Category')),
            ],
        ),
    ]
